name: Test

on:
  workflow_dispatch: {}

jobs:
  rc:
    name: Test
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: run sync
        run: |
          ./sync.bash install
